version: "3"
services:
  db:
    image: mysql:8
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQLDB_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
networks:
  backend:
    driver: bridge
volumes:
  db:
    driver: local