version: "3"
services:
  db:
    image: mysql:8
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=trpcdev
      - MYSQL_PASSWORD=trpcdev
      - MYSQLDB_DATABASE=intro_trpc
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
networks:
  backend:
    driver: bridge
volumes:
  db:
    driver: local